version: '3.8'
services:
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/grocery_list/
    restart: always
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000"

        