# Generated by Django 4.1.2 on 2022-10-20 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListItems',
            new_name='List',
        ),
    ]
