# Generated by Django 4.1.2 on 2022-10-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitems',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
