# Generated by Django 4.1.2 on 2022-10-21 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_listitems_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
