# Generated by Django 4.1.2 on 2022-10-28 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_listitems_list'),
        ('api', '0007_delete_list'),
    ]

    operations = [
    ]
